# This is a basic workflow to help you get started with Actions

on: [push, pull_request]
name: Test
jobs:
  exakat:
    name: Exakat Scanner III
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exakat
      uses: docker://exakat/exakat-ga
      with:
        ignore_rules: 'toto,Classes/StaticMethodsCalledFromObject,Security/DontEchoError,Php/WrongTypeForNativeFunction,Typehints/MissingReturntype,Structures/NoSubstrOne,Typehints/MissingReturntype,Structures/NoSubstrOne,Structures/UselessCasting,Structures/SwitchWithoutDefault,Functions/WrongReturnedType,Functions/UsesDefaultArguments,Structures/Noscream,Namespaces/HiddenUse,Functions/UsesDefaultArguments'
        ignore_dirs: '/src/Sculpin/Test,/src/Sculpin/Core,/src/Sculpin/Contrib,/src/Sculpin/Bundle'
